"""add cascade delete

Revision ID: 192d2831d9ac
Revises: 7e109bf4a6fc
Create Date: 2025-02-21 13:52:34.384446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192d2831d9ac'
down_revision = '7e109bf4a6fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('channel_user_id_fkey', 'channel', type_='foreignkey')
    op.create_foreign_key(None, 'channel', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('comment_vote', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('comment_vote', 'comment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('comment_vote_user_id_fkey', 'comment_vote', type_='foreignkey')
    op.drop_constraint('comment_vote_comment_id_fkey', 'comment_vote', type_='foreignkey')
    op.create_foreign_key(None, 'comment_vote', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment_vote', 'video_comment', ['comment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('video', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('video_user_id_fkey', 'video', type_='foreignkey')
    op.create_foreign_key(None, 'video', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('video_comment', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('video_comment_user_id_fkey', 'video_comment', type_='foreignkey')
    op.create_foreign_key(None, 'video_comment', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('video_tag_video_id_fkey', 'video_tag', type_='foreignkey')
    op.drop_constraint('video_tag_tag_id_fkey', 'video_tag', type_='foreignkey')
    op.create_foreign_key(None, 'video_tag', 'video', ['video_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'video_tag', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_tag', type_='foreignkey')
    op.drop_constraint(None, 'video_tag', type_='foreignkey')
    op.create_foreign_key('video_tag_tag_id_fkey', 'video_tag', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key('video_tag_video_id_fkey', 'video_tag', 'video', ['video_id'], ['id'])
    op.drop_constraint(None, 'video_comment', type_='foreignkey')
    op.create_foreign_key('video_comment_user_id_fkey', 'video_comment', 'users', ['user_id'], ['id'])
    op.alter_column('video_comment', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.create_foreign_key('video_user_id_fkey', 'video', 'users', ['user_id'], ['id'])
    op.alter_column('video', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'comment_vote', type_='foreignkey')
    op.drop_constraint(None, 'comment_vote', type_='foreignkey')
    op.create_foreign_key('comment_vote_comment_id_fkey', 'comment_vote', 'video_comment', ['comment_id'], ['id'])
    op.create_foreign_key('comment_vote_user_id_fkey', 'comment_vote', 'users', ['user_id'], ['id'])
    op.alter_column('comment_vote', 'comment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('comment_vote', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'channel', type_='foreignkey')
    op.create_foreign_key('channel_user_id_fkey', 'channel', 'users', ['user_id'], ['id'])
    op.alter_column('channel', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
