"""update video table

Revision ID: c11715d61bd7
Revises: dfc497439386
Create Date: 2025-05-18 13:36:16.313437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c11715d61bd7'
down_revision = 'dfc497439386'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('preview_ext', postgresql.ENUM('PNG', 'JPEG', 'WEBP', 'SVG', name='image_extensions_enum'), nullable=True))
    op.add_column('video', sa.Column('name', sa.String(length=255), nullable=False))
    op.alter_column('video', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.drop_column('video', 'preview')
    op.drop_column('video', 'title')
    op.add_column('video_metadatas', sa.Column('id', sa.UUID(), nullable=False))
    op.drop_constraint('video_metadatas_video_id_fkey', 'video_metadatas', type_='foreignkey')
    op.create_foreign_key(None, 'video_metadatas', 'video', ['id'], ['id'], ondelete='CASCADE')
    op.drop_column('video_metadatas', 'video_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_metadatas', sa.Column('video_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'video_metadatas', type_='foreignkey')
    op.create_foreign_key('video_metadatas_video_id_fkey', 'video_metadatas', 'video', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_column('video_metadatas', 'id')
    op.add_column('video', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('video', sa.Column('preview', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.alter_column('video', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.drop_column('video', 'name')
    op.drop_column('video', 'preview_ext')
    # ### end Alembic commands ###
