"""empty message

Revision ID: f278813bf419
Revises: 2c511cc6bd60
Create Date: 2025-05-10 18:00:52.128202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f278813bf419'
down_revision = '2c511cc6bd60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    image_extensions_enum = postgresql.ENUM(
        'PNG', 'JPEG', 'WEBP', 'SVG',
        name='image_extensions_enum'
    )
    image_extensions_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'users',
        sa.Column('avatar_ext', image_extensions_enum, nullable=True)
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_ext')
    # ### end Alembic commands ###
