"""reset channel avatar param

Revision ID: dfc497439386
Revises: f278813bf419
Create Date: 2025-05-13 10:13:52.736855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfc497439386'
down_revision = 'f278813bf419'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('avatar_ext', postgresql.ENUM('PNG', 'JPEG', 'WEBP', 'SVG', name='image_extensions_enum'), nullable=True))
    op.drop_column('channels', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('avatar', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('channels', 'avatar_ext')
    # ### end Alembic commands ###
