"""add is_public in courses

Revision ID: 6ca8ef4aed54
Revises: d69a63ba0a85
Create Date: 2025-04-13 18:30:23.227444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca8ef4aed54'
down_revision = 'd69a63ba0a85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'channels', ['id'])
    op.add_column('courses', sa.Column('is_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'is_public')
    op.drop_constraint(None, 'channels', type_='unique')
    # ### end Alembic commands ###
