"""empty message

Revision ID: d3be26b6c840
Revises: 2716430be8ab
Create Date: 2025-04-20 12:40:29.069386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3be26b6c840'
down_revision = '2716430be8ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_permissions', sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('users_permissions', 'expiration_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_permissions', 'expiration_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('users_permissions', 'granted_at')
    # ### end Alembic commands ###
