"""fck_unique

Revision ID: 22dbdf2fe391
Revises: 0138b6266d35
Create Date: 2025-05-29 16:59:36.416999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22dbdf2fe391'
down_revision = '0138b6266d35'
branch_labels = None
depends_on = None


def upgrade() -> None:

    op.execute("DELETE FROM courses_structure")


    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'courses', ['id'])
    op.create_unique_constraint(None, 'courses_structure', ['id'])
    op.create_unique_constraint(None, 'secret_info', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'video_metadatas', ['id'])
    op.create_unique_constraint(None, 'videos', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='unique')
    op.drop_constraint(None, 'video_metadatas', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'secret_info', type_='unique')
    op.drop_constraint(None, 'courses_structure', type_='unique')
    op.drop_constraint(None, 'courses', type_='unique')
    # ### end Alembic commands ###
