"""secret_info rename user_id column to id

Revision ID: 4c1aa2661225
Revises: 742c31a4b5e4
Create Date: 2025-04-23 15:16:38.360873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1aa2661225'
down_revision = '742c31a4b5e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secret_info', sa.Column('id', sa.UUID(), nullable=False))
    op.drop_constraint('secret_info_user_id_fkey', 'secret_info', type_='foreignkey')
    op.create_foreign_key(None, 'secret_info', 'users', ['id'], ['id'], ondelete='CASCADE')
    op.drop_column('secret_info', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secret_info', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'secret_info', type_='foreignkey')
    op.create_foreign_key('secret_info_user_id_fkey', 'secret_info', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('secret_info', 'id')
    # ### end Alembic commands ###
